version: "3.7"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        env_file: config/.env
        image: rabbitmq:3.8-management-alpine
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
          - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASSWORD}
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
    mongo:
      image: mongo
      env_file: /config/.env
      command: mongod --auth
      volumes:
        - C:\Users\rbblazquez\mongo_docker_volume\data:/data/db
        - C:\Users\rbblazquez\mongo_docker_volume\mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - C:\Users\rbblazquez\mongo_docker_volume\configdb:/data/configdb
      ports:
        - "27017:27017"
      restart: unless-stopped