services:
  django_server:
    build: .
    working_dir: /usr/src/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py wait_for_rabbit &&
            python manage.py runserver"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - mongo
      - mongo-express
      - rabbitmq
    container_name: django_server
    networks:
      - django_server

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - mongo_db

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  networks:
    rabbitmq_go_net:
      driver: bridge

    mongo_db:
      driver: bridge

    django_server:
      driver: bridge